import { bool, number, string, shape, oneOf } from 'prop-types';

// add custom prop type for media breakpoints

export default {
  columns: number,
  padded: bool,
  xs: number,
  sm: number,
  md: number,
  lg: number,
  xl: number,
  breakpoints: shape({
    sm: string.isRequired,
    md: string.isRequired,
    lg: string.isRequired,
    xl: string.isRequired,
  }),
  order: number,
  flow: oneOf([
    'row',
    'row-reverse',
    'column',
    'column-reverse',
    'nowrap',
    'wrap',
    'wrap-reverse',
    'row nowrap',
    'row wrap',
    'row wrap-reverse',
    'row-reverse nowrap',
    'row-reverse wrap',
    'row-reverse wrap-reverse',
    'column nowrap',
    'column wrap',
    'column wrap-reverse',
    'column-reverse nowrap',
    'column-reverse wrap',
    'column-reverse wrap-reverse',
    'initial',
    'inherit',
  ]),
  justify: oneOf([
    'flex-start',
    'flex-end',
    'center',
    'space-between',
    'space-around',
    'initial',
    'inherit',
  ]),
  align: oneOf([
    'flex-start',
    'flex-end',
    'center',
    'space-between',
    'space-around',
    'stretch',
    'initial',
    'inherit',
  ]),
  items: oneOf([
    'flex-start',
    'flex-end',
    'center',
    'baseline',
    'stretch',
    'initial',
    'inherit',
  ]),
};
